### ISSUE TITLE
Asset loading screen ends too early

### ISSUE THREAD

**Issue by TimJentzsch** [janhohenheim/foxtrot#257] opened 2023-04-10 09:05 UTC
The loading screen after you hit "Play" ends too early.
This is especially noticable on the web build, where you have to stare at this wall for some time until the game becomes playable:
![The wall you have to stare at](https://user-images.githubusercontent.com/13908946/230870586-ea8a8cc5-d7fd-4bfe-803b-be3bf555aa92.png)

**Comment by janhohenheim** [comment] 2024-02-01 18:30
Couldn't reproduce this on the newest version, so closing this for now.

**Closed by janhohenheim** 2024-02-01 18:30 UTC
Labels: bug
